### ISSUE TITLE
The server shuts down for no reason

### ISSUE THREAD

**Issue by Akak72** [ScerIO/PocketMine-MP-Android#92]
When I do not look at the application for a long time (about 20 minutes), the server shuts down, even when someone is playing on it.

**Comment by Tcode209** [comment]
## Pocketmine Problems huh....


### Why:
1.Because of an automatic launch was enabled
2.Power saving mode enabled


### Just follow these steps:
#### for Android 8.0.0 or later
Go to Settings >> Battery >> Launch >> Pocketmine-MP >> Turn off the switch to run in background!
#### for Some Android Versions
Go to Settings >> Battery >> Turn off power saving mode switch
